# --- WALLET CORE ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet-core
  template:
    metadata:
      labels:
        app: wallet-core
    spec:
      containers:
        - name: wallet-core
          image: payflow/wallet-core:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: PROFILE_ACTIVE
              value: "dev, k8s"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: "guest"
            - name: RABBITMQ_PASSWORD
              value: "guest"
            - name: DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/wallet_db"
            - name: DATASOURCE_USERNAME
              value: "postgres"
            - name: DATASOURCE_PASSWORD
              value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: wallet-core
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: wallet-core

---
# --- TRANSFER MANAGER ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transfer-manager
  template:
    metadata:
      labels:
        app: transfer-manager
    spec:
      containers:
        - name: transfer-manager
          image: payflow/transfer-manager:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: PROFILE_ACTIVE
              value: "dev, k8s"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: "guest"
            - name: RABBITMQ_PASSWORD
              value: "guest"
            - name: DATA_MONGODB_URI
              value: "mongodb://root:example@mongo:27017/transfer_db"
            - name: WALLET_CORE_URL
              value: "http://wallet-core:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: transfer-manager
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: transfer-manager

---
# --- NOTIFICATION SERVICE ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-svc
  template:
    metadata:
      labels:
        app: notification-svc
    spec:
      containers:
        - name: notification-svc
          image: payflow/notification-svc:latest
          imagePullPolicy: Never
          env:
            - name: PROFILE_ACTIVE
              value: "dev, k8s"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: "guest"
            - name: RABBITMQ_PASSWORD
              value: "guest"
            - name: JSM_EMAIL
              value: ""
            - name: JSM_PASSWORD
              value: ""